### ISSUE TITLE
Preview block

### ISSUE THREAD

**Issue by sidg28** [Arsenic-ATG/Tetris#22]
Make a portal where we can see next two blocks

**Comment by andrewrgarcia** [comment]
Hi Ankur, 
Can I be assigned to this issue? As you can see by my commit, I am working on it. 
Regards, 
Andrew

**Comment by andrewrgarcia** [comment]
@Arsenic-ATG How come the game with the [new changes](https://deploy-preview-52--tetrisplusplus.netlify.app/) (the 3 next tetrominos windows) is still not showing in the [main netlify site](https://tetrisplusplus.netlify.app/) ?

**Comment by Arsenic-ATG** [comment]
> @Arsenic-ATG How come the game with the [new changes](https://deploy-preview-52--tetrisplusplus.netlify.app/) (the 3 next tetrominos windows) is still not showing in the [main netlify site](https://tetrisplusplus.netlify.app/) ?

I see netlify cancelling the deploy as it didn't detect any change, this happens sometime ( I would look into the deployment setting there and try to fix it asap). For now, I have triggered a manual deploy, the site should up-to-date now.

**Comment by andrewrgarcia** [comment]
> > @Arsenic-ATG How come the game with the [new changes](https://deploy-preview-52--tetrisplusplus.netlify.app/) (the 3 next tetrominos windows) is still not showing in the [main netlify site](https://tetrisplusplus.netlify.app/) ?
> 
> I see netlify cancelling the deploy as it didn't detect any change, this happens sometime ( I would look into the deployment setting there and try to fix it asap). For now, I have triggered a manual deploy, the site should up-to-date now.

Great! Game looks :fire:
