### ISSUE TITLE
Typo in README.md

### ISSUE THREAD

**Issue by Arsenic-ATG** [Arsenic-ATG/Tetris#49]
There is a typo on line 37 of README.md

**Comment by bhavy2202** [comment]
Assign me please

**Comment by Arsenic-ATG** [comment]
@bhavy2202 sorry, but a PR was just created solving the issue. ( #48 )

If you are looking for other quick contributions, then try looking at other issues marked as `good-first-issue`

**Comment by Arsenic-ATG** [comment]
Or if you want more contributions ( non-code or low code) for hacktoberfest then try looking for my other repositories.

**Comment by bhavy2202** [comment]
I will look into your repository
Thank you
